Repository dnd-side-project/dnd-13th-3-frontend, pull requests merged in 2025-08, with the labels that each got.

#2 ✨ Feat: 메인페이지 상단 컴포넌트 구현
  biome.json
  next.config.ts
  package-lock.json
  package.json
  postcss.config.mjs
  public/images/logos/MinuLogo.svg
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/GoalTab.tsx
  src/components/Logo.tsx
  src/components/TabContent.tsx
  src/components/TabSwitcher.tsx
  src/components/TimerTab.tsx
  src/store/tabStore.ts
  tailwind.config.ts
Labels: Feature, priority: medium

#4 [FEAT] - 타이머 페이지 구현 및 기본 레이아웃 재작업
  public/images/logos/ArrowBottom.svg
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/onboarding/page.tsx
  src/app/(main)/challenge/page.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/page.tsx
  src/app/(main)/record/page.tsx
  src/app/(main)/timer/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/TabContent.tsx
  src/components/common/BottomNavbar.tsx
  src/components/common/GoalTab.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/components/timer/CircularTimer.tsx
  src/components/timer/ConfirmEndModal.tsx
  src/components/timer/MissionOptionButton.tsx
  src/components/timer/MissionSelectButton.tsx
  src/components/timer/MissionSelectModal.tsx
  src/components/timer/ResultModal.tsx
  src/components/timer/TabSwitcher.tsx
  src/components/timer/TimeDisplay.tsx
  src/components/timer/TimerContainer.tsx
  src/components/timer/TimerDisplay.tsx
  src/components/timer/TimerTab.tsx
  src/components/timer/index.ts
  src/hooks/useTimer.ts
  src/lib/constants.ts
  src/store/tabStore.ts
  tailwind.config.ts
Labels: Feature, priority: medium

#6 ✨ Feat: 스플래시, 로그인 페이지 구현
  package-lock.json
  package.json
  public/images/logos/MinuCharacter.svg
  public/images/logos/MinuLoginLogo.svg
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(main)/main/page.tsx
  src/app/globals.css
  src/app/page.tsx
  src/app/splash/page.tsx
  src/components/LoginLogo.tsx
  src/components/MinuCharacter.tsx
  src/components/common/BottomNavbar.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/components/layout/AuthLayout.tsx
  src/components/login/CloudLayer.tsx
  src/components/login/GoogleLoginButton.tsx
  src/components/login/LoginContent.tsx
  src/components/login/index.ts
  src/components/timer/TabSwitcher.tsx
  src/components/timer/index.ts
  src/hooks/useTimer.ts
  tailwind.config.ts
Labels: Feature, priority: medium

#8 ✨ Feat: 온보딩 페이지 구현
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/onboarding/page.tsx
  src/app/layout.tsx
  src/components/onboarding/BackHeader.tsx
  src/components/onboarding/BottomBar.tsx
  src/components/onboarding/Container.tsx
  src/components/onboarding/GoalSelect.tsx
  src/components/onboarding/NicknameField.tsx
  src/components/onboarding/Onboarding.tsx
  src/components/onboarding/SelectableButton.tsx
  src/components/onboarding/SelectedIndicator.tsx
  src/components/onboarding/StepProgress.tsx
  src/components/onboarding/TimeTarget.tsx
  src/components/onboarding/TitleSection.tsx
  src/components/onboarding/index.ts
  src/hooks/useGoalSelection.ts
  src/hooks/useNicknameInput.ts
  src/hooks/useTimeTarget.ts
  src/lib/onboarding.ts
Labels: Feature, priority: high

#35 ✨Feat: 챌린지 히스토리, 챌린지 초대, 수락, 프로필 수정 기능 구현
  public/images/logos/Alert.svg
  public/images/logos/BackBtnWhite.svg
  public/images/logos/ChallengeCantJoin.svg
  public/images/logos/ChallengeEmpty.svg
  public/images/logos/ChallengeFirst.svg
  public/images/logos/ChallengeFull.svg
  public/images/logos/ChallengeSecond.svg
  public/images/logos/ChallengeText.svg
  public/images/logos/ChallengeThird.svg
  public/images/logos/ChallengedCharater1.svg
  public/images/logos/ChallengedCharater2.svg
  public/images/logos/ChallengedCharater3.svg
  public/images/logos/ChallengedCharater4.svg
  public/images/logos/ChallengedCharater5.svg
  public/images/logos/ChallengedCharater6.svg
  public/images/logos/CircleCheck.svg
  public/images/logos/HourglassLast.svg
  public/images/logos/Latter.svg
  src/app/(main)/challenge/page.tsx
  src/app/(main)/record/page.tsx
  src/app/history/[id]/page.tsx
  src/app/history/page.tsx
  src/components/challenge/ChallengeCreateForm.tsx
  src/components/challenge/ChallengeDetailClient.tsx
  src/components/challenge/ChallengeEmptyState.tsx
  src/components/challenge/ChallengeEmptyStateClient.tsx
  src/components/challenge/ChallengeFullModal.tsx
  src/components/challenge/ChallengeHeader.tsx
  src/components/challenge/ChallengeHistoryClient.tsx
  src/components/challenge/ChallengeHistoryTab.tsx
  src/components/challenge/ChallengeOngoing.tsx
  src/components/challenge/ChallengeSuccessModal.tsx
  src/components/challenge/InviteFriendModal.tsx
  src/components/challenge/index.ts
  src/components/join/JoinChallengeClient.tsx
  src/components/main/MainContent.tsx
  src/components/main/ScreenTimeInfo.tsx
  src/components/onboarding/Onboarding.tsx
  src/components/setting/ProfileEditClient.tsx
  src/components/setting/SettingPageClient.tsx
  src/components/timer/ConfirmEndModal.tsx
  src/components/timer/ResultModal.tsx
  src/components/timer/TimerContainer.tsx
  src/lib/api/challenge.ts
  src/lib/api/index.ts
  src/lib/challenge.ts
  src/lib/goals.ts
Labels: Feature, priority: critical

#42 [FEAT] - 리포트 페이지 구현
  public/images/logos/Icon/Normal/Pencil.svg
  public/images/logos/Icon/Normal/over.svg
  public/images/logos/Icon/Normal/under.svg
  public/images/logos/MCharacter1.svg
  public/images/logos/MCharacter2.svg
  public/images/logos/MCharacter3.svg
  public/images/logos/MCharacter4.svg
  public/images/logos/MCharacter5.svg
  public/images/logos/MCharacter6.svg
  public/images/logos/screentime.svg
  public/images/logos/screentimeOver.svg
  src/app/(main)/main/page.tsx
  src/app/(main)/record/page.tsx
  src/components/main/MainContent.tsx
  src/components/main/ProgressSection.tsx
  src/components/main/StatsCards.tsx
  src/components/record/RecordClient.tsx
  src/lib/api/aiFeedback.ts
  src/lib/api/screentime.ts
  src/types/aiFeedback.ts
  src/types/report.ts
  src/types/screentime.ts
  src/utils/character.ts
Labels: Feature, priority: critical

#47 Hotfix/qa2
  src/components/main/GoalEditModal.tsx
  src/components/main/MainContent.tsx
  src/components/main/ProgressSection.tsx
  src/components/main/ScreenTimeInfo.tsx
  src/components/main/StatsCards.tsx
  src/components/record/RecordClient.tsx
Labels: Hotfix
